production:
  adapter: postgresql
  encoding: unicode
  database: postgres_production
  pool: 20
  url: <%= ENV['DATABASE_URL'] %>

development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: postgres_development
  pool: 5
  username: rails
  password: password

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: postgres_test
  pool: 5
  username: rails
  password: password
