production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RDS_DB_NAME'] %>
  pool: 20
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: postgres_development
  pool: 5
  username: rails
  password: password

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: postgres_test
  pool: 5
  username: rails
  password: password
